### ISSUE TITLE
TypeError: range() integer end argument expected, got float

### ISSUE THREAD

**Issue by bingo9062** [tejaslodaya/tensorflow-signs-cnn#1]
hello:
 
when i run python   tf_main.py i got this:
File "tf_main.py", line 13, in <module
/tf_utils.py", line 172
cnn_utils.py", line 55, in random_mini_batches
TypeError: range() integer end argument expected, got float
could you help me ?

**Comment by tejaslodaya** [comment]
Hi @bingo9062 
Which version of python are you using?

**Comment by bingo9062** [comment]
i am using python2.7

**Comment by tejaslodaya** [comment]
Please upgrade to Python 3.5 and above. 

Deeplearning community is moving towards ending support for 2.7
Read here: https://news.ycombinator.com/item?id=15707956

**Comment by bingo9062** [comment]
thank you！I will try after upgrade python

**Comment by tejaslodaya** [comment]
@bingo9062 
I am closing the issue for now.
